<?php

/**
* @files
* lets users add private annotations to nodes.
*
* Adds a text field when a node is displayed
* so that authenticated users may make notes.
*/

/**
* Implementation of hook_menu().
*/
function annotate_menu() {
  $items['admin/config/annotate'] = array(
    'title' => 'Node annotation',
    'description' => 'Adjust node annotation options.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'files path' => drupal_get_path('module', 'system'),
   );

   $items['admin/config/annotate/settings'] = array(
     'title' => 'Annotation settings',
     'description' => 'Change how annotation behave.',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('annotate_admin_settings'),
     'access arguments' => array('administer site configuration'),
     'type' => MENU_NORMAL_ITEM,
     'file' => 'annotate.admin.inc',
    );

    return $items;
}

/**
* Implements hook_node_load()
*/

function annotate_node_load($node,$type){
  global $user;
  foreach ($nodes as $node) {
    if($user->uid != $node->uid) {
      unset($node->annotation);
    }
  }

}
